name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
      env:
        PKGDEST: /home/builder/packages
    steps:
      - run: echo "$GITHUB_REPOSITORY"
      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
      - run: pacman -Syu git fakeroot bc docbook-xsl elfutils inetutils kmod xmlto base-devel gnupg --noconfirm
      - run: useradd -m builder
      - run: mkdir -p /home/builder/packages
      - uses: actions/checkout@v2.3.2
      - run: mv ./$GITHUB_REPOSITORY /home/builder/
      - run: su builder -c "gpg --import --batch --passphrase ${{ secrets.GPG_PASS }} <(echo -e "${{ secrets.GPG_SECRET}}")"
      - run: su builder -c "cd /home/builder/$GITHUB_REPOSITORY; makepkg -s --sign"
