name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
    steps:
      - run: pacman -Syu git fakeroot bc docbook-xsl elfutils inetutils kmod xmlto base-devel gnupg --noconfirm
      - run: useradd -m builder
      - run: su builder
      - run: mkdir -p ~/packages
      - uses: actions/checkout@v2.3.2
      - run: echo -e "${{ secrets.GPG_SECRET}}" >> key.gpg
      - run: gpg --import --batch --passphrase ${{ secrets.GPG_PASS }} key.gpg
      - run: makepkg -s --sign
