name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, JPyke3-CI-Testing ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
      env:
        PKGDEST: /home/builder/packages
    defaults:
      run:
        shell: bash
    steps:
      - run: pacman -Syu git fakeroot bc docbook-xsl elfutils inetutils kmod xmlto base-devel gnupg --noconfirm
        name: Update image and Download Depends
      - uses: actions/checkout@v2
        name: Checkout the Repository
      - run: useradd -m builder
        name: Add Builder User
      - run: cp -r /__w/"$(echo -e "$GITHUB_REPOSITORY" | sed 's/.*\///g')"/"$(echo -e "$GITHUB_REPOSITORY" | sed 's/.*\///g')" /home/builder/
        name: Copy Repository to Builder Home Directory
      - run: mkdir -p /home/builder/packages
        name: Create final package location
      - run: echo -e "${{ secrets.GPG_SECRET}}" >> /home/builder/key.gpg
        name: Export GPG key from secret to a file
      - run: chown builder:builder -R /home/builder
        name: Give the builder user ownership of it's own home dir
      - name: Import GPG key CD to makepkg dir and compile the kernel
        run: |
          su builder -c\
          "export GPG_TTY=$(tty);\
          gpg --import --batch --passphrase \"${{ secrets.GPG_PASS }}\" /home/builder/key.gpg;\
          cd /home/builder/\"$(echo -e \"$GITHUB_REPOSITORY\" | sed 's/.*\///g')\";\
          makepkg -s --sign"
      - uses: actions/upload-artifact@v2
        name: Generate Artifacts
        if: ${{ always() }}
        with:
          path: /home/builder/packages/
