name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
      env:
        PKGDEST: /home/builduser/packages
    steps:
      - run: pacman -Syu git fakeroot bc docbook-xsl elfutils inetutils kmod xmlto base-devel gnupg pahole cpio --noconfirm
        name: Update image and Download Depends
      - uses: actions/checkout@v2
        name: Checkout the Repository
      - run: useradd -m builduser
        name: Add Builder User
      - run: cp -r /__w/"$(echo -e "$GITHUB_REPOSITORY" | sed 's/.*\///g')"/"$(echo -e "$GITHUB_REPOSITORY" | sed 's/.*\///g')" /home/builduser/
        name: Copy Repository to Builder Home Directory
      - run: mkdir -p /home/builduser/packages
        name: Create final package location
      - run: chown builduser:builduser -R /home/builduser
        name: Chown builder home dir
      - run: su builduser -c "cd /home/builduser/"$(echo -e "$GITHUB_REPOSITORY" | sed 's/.*\///g')"; makepkg -s"
        name: Compile the Kernel
      - uses: actions/upload-artifact@v2
        name: Generate Artifacts
        if: ${{ always() }}
        with:
          path: /home/builduser/packages/
