name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
      env:
        PKGDEST: /home/builder/packages
    steps:
      - run: pacman -Syu git fakeroot bc docbook-xsl elfutils inetutils kmod xmlto base-devel gnupg --noconfirm
      - run: useradd -m builder
      - run: mkdir -p /home/builder/packages
      - uses: actions/checkout@v2.3.2
      - run: bash -c "mv ./"$(sed 's/.*\///g' <(echo -e "$GITHUB_REPOSITORY"))" /home/builder/"
      - run: su builder -c "gpg --import --batch --passphrase ${{ secrets.GPG_PASS }} <(echo -e "${{ secrets.GPG_SECRET}}")"
      - run: bash -c "su builder -c "cd /home/builder/"$(sed 's/.*\///g' <(echo -e "$GITHUB_REPOSITORY"))"; makepkg -s --sign""
